# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailoutlet',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
