# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_retailoutlet_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailoutlet',
            options={'verbose_name': 'point de vente', 'verbose_name_plural': 'points de vente'},
        ),
        migrations.AlterField(
            model_name='retailoutlet',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='est publi\xe9?'),
        ),
        migrations.AlterField(
            model_name='retailoutlet',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
    ]
