# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_auto_20170705_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailoutlet',
            options={'ordering': ('name',), 'verbose_name': 'point de vente', 'verbose_name_plural': 'points de vente'},
        ),
    ]
