# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0026_contribution_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='in_toc',
        ),
        migrations.AddField(
            model_name='articlemembership',
            name='in_toc',
            field=models.BooleanField(default=True, verbose_name='montr\xe9 dans le table de mati\xe8re'),
        ),
    ]
