# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0027_auto_20171012_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
