# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 14:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('publish', '0029_auto_20171019_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cover',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
    ]
