# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0031_auto_20180121_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='published_online',
            field=models.BooleanField(default=False, verbose_name='publi\xe9 en ligne'),
        ),
    ]
