# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0032_issue_published_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(related_name='_article_related_articles_+', to='publish.Article'),
        ),
    ]
