# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0033_article_related_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='_article_related_articles_+', to='publish.Article'),
        ),
    ]
